# Generated by Django 5.1.4 on 2025-09-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_salesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='store.goods'),
        ),
    ]
